# Generated by Django 6.0.3 on 2026-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_seats',
            field=models.IntegerField(default=15),
        ),
    ]
