# Generated by Django 6.0.3 on 2026-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_max_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_groups',
            field=models.ManyToManyField(blank=True, help_text="Qo'shimcha guruhlar", related_name='additional_students', to='main.group'),
        ),
    ]
