# Generated by Django 6.0.3 on 2026-06-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_additional_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='additional_groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.group'),
        ),
    ]
